name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install tools
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Copy www to public
        run: cp -r www public
      - name: Build
        run: wasm-pack build --target web --out-dir public/js
      - name: Remove .gitignore added from wasm-pack
        run: rm public/.gitignore
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
